version: "3.9"
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/data/db"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./cmd/api/Dockerfile
  #   ports:
  #     - "4000:8080"  # Adjust based on your configuration
  #   environment:
  #     CONFIG_FILE: config.yaml
  #   volumes:
  #     - .:.
  #   depends_on:
  #     - postgres
  #     - redis

volumes:
  postgres_data:
  redis_data:
