host: 172.17.0.1
port: 4000
db_port: 5432
db_name: postgres
db_user: postgres
db_password: postgres
# db_host: 172.17.0.1
db_host: 172.18.0.3
redis_port: 6379
redis_password:
redis_db: 0
redis_host: 172.18.0.2